<list>
  <Rectangle>
    <position>
      <x>176</x>
      <y>214</y>
    </position>
    <width>153</width>
    <height>164</height>
  </Rectangle>
  <Rectangle>
    <position>
      <x>821</x>
      <y>228</y>
    </position>
    <width>155</width>
    <height>129</height>
  </Rectangle>
  <Rectangle>
    <position>
      <x>594</x>
      <y>391</y>
    </position>
    <width>164</width>
    <height>124</height>
  </Rectangle>
  <Rectangle>
    <position>
      <x>836</x>
      <y>54</y>
    </position>
    <width>1</width>
    <height>0</height>
  </Rectangle>
</list>